import { NextRequest, NextResponse } from 'next/server';

// TODO: Replace with real image generation using Satori/Resvg
// This is a placeholder that returns a simple data URL
function generatePlaceholderImage(scene: string): string {
  // Create a simple SVG as placeholder
  const svg = `
    <svg width="800" height="600" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" style="stop-color:#1e3a8a;stop-opacity:1" />
          <stop offset="100%" style="stop-color:#7c3aed;stop-opacity:1" />
        </linearGradient>
      </defs>
      <rect width="800" height="600" fill="url(#bg)"/>
      <text x="400" y="200" font-family="Arial, sans-serif" font-size="32" font-weight="bold" text-anchor="middle" fill="white">
        Rift Rewind 2025
      </text>
      <text x="400" y="250" font-family="Arial, sans-serif" font-size="24" text-anchor="middle" fill="#e5e7eb">
        ${scene.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}
      </text>
      <text x="400" y="350" font-family="Arial, sans-serif" font-size="18" text-anchor="middle" fill="#d1d5db">
        Your League of Legends Year in Review
      </text>
      <text x="400" y="500" font-family="Arial, sans-serif" font-size="14" text-anchor="middle" fill="#9ca3af">
        Generated by Rift Rewind • Powered by Riot Games API
      </text>
    </svg>
  `;
  
  // Convert SVG to base64 data URL
  const base64 = Buffer.from(svg).toString('base64');
  return `data:image/svg+xml;base64,${base64}`;
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ scene: string }> }
) {
  const resolvedParams = await params;
  try {
    const scene = resolvedParams.scene;
    
    // TODO: Implement real image generation with Satori + Resvg
    // This would involve:
    // 1. Fetch scene data for the user
    // 2. Create a React component with the scene visualization
    // 3. Use Satori to convert React to SVG
    // 4. Use Resvg to convert SVG to PNG
    // 5. Return the PNG as a data URL or upload to CDN
    
    const imageUrl = generatePlaceholderImage(scene);
    
    return NextResponse.json({
      url: imageUrl,
      scene: scene,
      // TODO: Add metadata for social sharing
      metadata: {
        title: `My ${scene.replace(/_/g, ' ')} - Rift Rewind 2025`,
        description: 'Check out my League of Legends year in review!',
        width: 800,
        height: 600
      }
    });
  } catch (error) {
    console.error('Share API error:', error);
    
    return NextResponse.json(
      { error: 'Failed to generate share image' },
      { status: 500 }
    );
  }
}

// Also support POST for dynamic image generation with custom data
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ scene: string }> }
) {
  try {
    const resolvedParams = await params;
    const scene = resolvedParams.scene;
    const body = await request.json();
    
    // TODO: Use body data to customize the generated image
    // const { playerName, sceneData, agentId } = body;
    
    const imageUrl = generatePlaceholderImage(scene);
    
    return NextResponse.json({
      url: imageUrl,
      scene: scene
    });
  } catch (error) {
    console.error('Share API error:', error);
    
    return NextResponse.json(
      { error: 'Failed to generate share image' },
      { status: 500 }
    );
  }
}